#
# Jekyll basic configurations
#

# Re-include theme example pages for development
exclude:        []

#
# Almace Scaffolding settings
#

# Enable development mode
dev:            true

# Reset base to root for localhost development
base:           null

# CDN location for development
# file:           http://sparanoid.s3-website-us-east-1.amazonaws.com

# Force UTF-8 since local server doesn't send charset in their respond header
force_utf_8:    true

# Disalbe custom gems (jekyll-last-modified-at) for better performance
gems:           []
